#!/usr/bin/env python3
"""Generate roms_embedded.c: the ColecoVision BIOS, or nothing at all.

The ColecoVision OS-7 BIOS is copyrighted Coleco firmware and is not
redistributed by this project (COMPLIANCE.md). --none is therefore the
SHIPPING configuration, not an error path: it emits a NULL table so a
checkout with no ROM still builds and runs, with the app asking the user to
import one.

usage: embed-roms.py <out.c> <OS7.rom>
       embed-roms.py --none <out.c>
"""

import sys
from pathlib import Path

HEADER = """/* Generated by tools/roms/embed-roms.py -- do not edit.
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
#include <stdint.h>

"""


def main():
    args = sys.argv[1:]
    if args and args[0] == "--none":
        if len(args) != 2:
            sys.exit(__doc__)
        Path(args[1]).write_text(
            HEADER
            + "/* No BIOS embedded -- the shipping configuration. */\n"
            + "const uint8_t *const coleco_embedded_bios = 0;\n")
        return 0

    if len(args) != 2:
        sys.exit(__doc__)
    out, rom = Path(args[0]), Path(args[1])
    data = rom.read_bytes()
    if len(data) != 0x2000:
        sys.exit(f"{rom}: expected 8192 bytes, got {len(data)}")

    body = [HEADER,
            "/* WITH_COLECO_ROMS=ON: a developer build. NOT redistributable.\n"
            " * See COMPLIANCE.md. */\n",
            "static const uint8_t bios[8192] = {\n"]
    for i in range(0, len(data), 16):
        body.append("    " + ",".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
    body.append("};\n\nconst uint8_t *const coleco_embedded_bios = bios;\n")
    out.write_text("".join(body))
    return 0


if __name__ == "__main__":
    sys.exit(main())
