#!/usr/bin/env python3
"""Generate the OS7 debugger symbol table.

Source (local, see COMPLIANCE.md for provenance): the Ghidra-style listing in
~/Workspace/os7lib/sre, taking named code labels and function signatures
(BYTE_/DAT_/UNK_/PTR_ data labels skipped) with the address of the next
`OS7:ram:XXXX` line.

The ADAM app extracts two tables here, EOS and OS7. The ColecoVision has no
EOS -- it is the ADAM's operating system, and the console does not have one --
so this is the OS7 half of fujinet-go-adam-desktop/tools/symbols/
extract-symbols.py with the EOS half removed rather than a second
implementation.

What is generated is a table of FACTS: names and addresses from a published
disassembly, containing no program code. COMPLIANCE.md records why that
distinction matters and why the BIOS itself is not redistributed.

Outputs (both committed, so a build needs neither this script nor its source):
  core/debugger/symbols/os7.sym     the .sym text, loadable at run time
  core/debugger/symbols_builtin.c   the same table as a C string

Usage: extract-symbols.py [--os7 FILE] [--check]

--check regenerates into memory and compares against what is committed,
exiting non-zero if they differ. That is what makes the "Generated by" header
on symbols_builtin.c an actual claim rather than a comment.
"""

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
WS = Path.home() / "Workspace"


def extract_os7(listing_path):
    syms = {}
    pending = []
    label_re = re.compile(r"^\s{8,}([A-Za-z_][A-Za-z0-9_]*):")
    func_re = re.compile(
        r"^\s{8,};\s*(?:undefined|void|byte|int|char)\s+([A-Za-z_]\w*)\s*\(")
    addr_re = re.compile(r"^OS7:ram:([0-9a-f]{1,4})\s")
    for line in listing_path.read_text(errors="replace").splitlines():
        m = label_re.match(line)
        if m:
            name = m.group(1)
            if not name.startswith(("BYTE_", "DAT_", "UNK_", "PTR_")):
                pending.append(name)
            continue
        m = func_re.match(line)
        if m:
            pending.append(m.group(1))
            continue
        m = addr_re.match(line)
        if m and pending:
            addr = int(m.group(1), 16)
            for name in pending:
                syms.setdefault(addr, name.rstrip("_"))
            pending = []
    return syms


HEADER = "OS7 symbols: os7lib SRE listing labels"


def sym_text(syms):
    lines = [f"# {HEADER}", "# Generated by tools/symbols/extract-symbols.py"]
    for addr in sorted(syms):
        lines.append(f"{addr:04X} {syms[addr]}")
    return "\n".join(lines) + "\n"


def c_string(text):
    out = []
    for line in text.splitlines():
        esc = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'    "{esc}\\n"')
    return "\n".join(out)


def builtin_text(syms):
    return (
        '/* Generated by tools/symbols/extract-symbols.py -- do not edit.\n'
        ' * The built-in OS-7 symbol table. The ColecoVision has no EOS, so the\n'
        " * ADAM app's second table has no counterpart here.\n"
        ' *\n'
        ' * A table of FACTS -- names and addresses from published\n'
        ' * disassemblies -- containing no program code. See COMPLIANCE.md.\n'
        ' * SPDX-License-Identifier: GPL-3.0-or-later\n'
        ' */\n'
        '\n'
        '#include "symbols.h"\n'
        '\n'
        'const char colecodebug_builtin_os7_sym[] =\n'
        f'{c_string(sym_text(syms))};\n'
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--os7", type=Path,
                    default=WS / "os7lib" / "sre" / "os7lib-dkong.txt")
    ap.add_argument("--check", action="store_true",
                    help="compare against the committed files instead of "
                         "rewriting them")
    args = ap.parse_args()

    if not args.os7.exists():
        print(f"OS7 listing not found: {args.os7}", file=sys.stderr)
        return 2

    syms = extract_os7(args.os7)
    if not syms:
        print("no symbols extracted -- has the listing format changed?",
              file=sys.stderr)
        return 2

    sym_path = REPO / "core" / "debugger" / "symbols" / "os7.sym"
    builtin_path = REPO / "core" / "debugger" / "symbols_builtin.c"
    want_sym = sym_text(syms)
    want_builtin = builtin_text(syms)

    if args.check:
        bad = 0
        for path, want in ((sym_path, want_sym), (builtin_path, want_builtin)):
            have = path.read_text() if path.exists() else None
            if have != want:
                print(f"{path.relative_to(REPO)} differs from what this "
                      f"script generates", file=sys.stderr)
                bad = 1
        if not bad:
            print(f"OS7: {len(syms)} symbols, committed files match")
        return bad

    sym_path.parent.mkdir(parents=True, exist_ok=True)
    sym_path.write_text(want_sym)
    builtin_path.write_text(want_builtin)
    print(f"OS7: {len(syms)} symbols -> {sym_path.relative_to(REPO)}, "
          f"{builtin_path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
