/*
 * Symbol tables (internal to the colecodebug engine).
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef COLECODEBUG_SYMBOLS_H
#define COLECODEBUG_SYMBOLS_H

#include <stdint.h>

#define SYM_MAX_TABLES 8

typedef struct {
    uint16_t addr;
    char name[48];
} sym_entry;

typedef struct {
    char name[16];
    sym_entry *entries; /* sorted by address */
    int count, cap;
    uint16_t lo, hi;
} sym_table;

typedef struct {
    sym_table tables[SYM_MAX_TABLES];
    int count;
} sym_tables;

int  symtabs_load_text(sym_tables *st, const char *text, const char *name);
int  symtabs_load_file(sym_tables *st, const char *path, const char *name);
const char *symtabs_at(const sym_tables *st, uint16_t addr, uint16_t *offset);
int  symtabs_find(const sym_tables *st, const char *name, uint16_t *addr);
void symtabs_free(sym_tables *st);

/* Built-in tables generated by tools/symbols/extract-symbols.py into
 * symbols_builtin.c (committed). */
extern const char colecodebug_builtin_eos_sym[];
extern const char colecodebug_builtin_os7_sym[];

#endif /* COLECODEBUG_SYMBOLS_H */
